import type { Dividend, Holding, HoldingWithPrice, PortfolioSnapshot } from '../types/portfolio';

const USD_CAD = 1.36;
const EUR_CAD = 1.47;

type MockHolding = Omit<
  HoldingWithPrice,
  'weight' | 'targetValue' | 'targetDeltaValue' | 'targetDeltaPercent'
>;

const RAW_HOLDINGS: MockHolding[] = [
  // Stocks
  {
    id: '1',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    assetType: 'stock',
    account: 'tfsa',
    quantity: 50,
    costBasis: 155.0,
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPrice: 189.84,
    currentPriceCad: 189.84 * USD_CAD,
    marketValueCad: 50 * 189.84 * USD_CAD,
    costValueCad: 50 * 155.0 * USD_CAD,
    gainLoss: 50 * (189.84 - 155.0) * USD_CAD,
    gainLossPercent: ((189.84 - 155.0) / 155.0) * 100,
    dailyChangePercent: 1.24,
    targetWeight: 12,
    createdAt: '2023-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  {
    id: '2',
    symbol: 'MSFT',
    name: 'Microsoft Corp.',
    assetType: 'stock',
    account: 'rrsp',
    quantity: 30,
    costBasis: 310.0,
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPrice: 415.52,
    currentPriceCad: 415.52 * USD_CAD,
    marketValueCad: 30 * 415.52 * USD_CAD,
    costValueCad: 30 * 310.0 * USD_CAD,
    gainLoss: 30 * (415.52 - 310.0) * USD_CAD,
    gainLossPercent: ((415.52 - 310.0) / 310.0) * 100,
    dailyChangePercent: -0.83,
    targetWeight: 10,
    createdAt: '2023-02-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  {
    id: '3',
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    assetType: 'stock',
    account: 'taxable',
    quantity: 25,
    costBasis: 420.0,
    currency: 'USD',
    exchange: 'NASDAQ',
    currentPrice: 875.4,
    currentPriceCad: 875.4 * USD_CAD,
    marketValueCad: 25 * 875.4 * USD_CAD,
    costValueCad: 25 * 420.0 * USD_CAD,
    gainLoss: 25 * (875.4 - 420.0) * USD_CAD,
    gainLossPercent: ((875.4 - 420.0) / 420.0) * 100,
    dailyChangePercent: 3.47,
    targetWeight: 8,
    createdAt: '2023-03-10T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  {
    id: '4',
    symbol: 'TD.TO',
    name: 'Toronto-Dominion Bank',
    assetType: 'stock',
    account: 'tfsa',
    quantity: 150,
    costBasis: 85.0,
    currency: 'CAD',
    exchange: 'TSX',
    currentPrice: 81.24,
    currentPriceCad: 81.24,
    marketValueCad: 150 * 81.24,
    costValueCad: 150 * 85.0,
    gainLoss: 150 * (81.24 - 85.0),
    gainLossPercent: ((81.24 - 85.0) / 85.0) * 100,
    dailyChangePercent: -0.42,
    targetWeight: 8,
    createdAt: '2022-11-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  {
    id: '5',
    symbol: 'RY.TO',
    name: 'Royal Bank of Canada',
    assetType: 'stock',
    account: 'rrsp',
    quantity: 80,
    costBasis: 120.0,
    currency: 'CAD',
    exchange: 'TSX',
    currentPrice: 135.88,
    currentPriceCad: 135.88,
    marketValueCad: 80 * 135.88,
    costValueCad: 80 * 120.0,
    gainLoss: 80 * (135.88 - 120.0),
    gainLossPercent: ((135.88 - 120.0) / 120.0) * 100,
    dailyChangePercent: 0.61,
    targetWeight: 8,
    createdAt: '2022-12-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  // ETFs
  {
    id: '6',
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    assetType: 'etf',
    account: 'rrsp',
    quantity: 40,
    costBasis: 380.0,
    currency: 'USD',
    exchange: 'NYSE',
    currentPrice: 481.55,
    currentPriceCad: 481.55 * USD_CAD,
    marketValueCad: 40 * 481.55 * USD_CAD,
    costValueCad: 40 * 380.0 * USD_CAD,
    gainLoss: 40 * (481.55 - 380.0) * USD_CAD,
    gainLossPercent: ((481.55 - 380.0) / 380.0) * 100,
    dailyChangePercent: 0.95,
    targetWeight: 14,
    createdAt: '2022-06-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  {
    id: '7',
    symbol: 'VFV.TO',
    name: 'Vanguard S&P 500 Index ETF (CAD)',
    assetType: 'etf',
    account: 'tfsa',
    quantity: 200,
    costBasis: 88.0,
    currency: 'CAD',
    exchange: 'TSX',
    currentPrice: 112.4,
    currentPriceCad: 112.4,
    marketValueCad: 200 * 112.4,
    costValueCad: 200 * 88.0,
    gainLoss: 200 * (112.4 - 88.0),
    gainLossPercent: ((112.4 - 88.0) / 88.0) * 100,
    dailyChangePercent: 1.02,
    targetWeight: 12,
    createdAt: '2022-07-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  // Crypto
  {
    id: '8',
    symbol: 'BTC-CAD',
    name: 'Bitcoin',
    assetType: 'crypto',
    account: 'taxable',
    quantity: 0.85,
    costBasis: 42000.0,
    currency: 'CAD',
    exchange: 'CCC',
    currentPrice: 87450.0,
    currentPriceCad: 87450.0,
    marketValueCad: 0.85 * 87450.0,
    costValueCad: 0.85 * 42000.0,
    gainLoss: 0.85 * (87450.0 - 42000.0),
    gainLossPercent: ((87450.0 - 42000.0) / 42000.0) * 100,
    dailyChangePercent: 4.82,
    targetWeight: 6,
    createdAt: '2023-01-20T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  {
    id: '9',
    symbol: 'ETH-CAD',
    name: 'Ethereum',
    assetType: 'crypto',
    account: 'taxable',
    quantity: 5.0,
    costBasis: 2200.0,
    currency: 'CAD',
    exchange: 'CCC',
    currentPrice: 4380.0,
    currentPriceCad: 4380.0,
    marketValueCad: 5.0 * 4380.0,
    costValueCad: 5.0 * 2200.0,
    gainLoss: 5.0 * (4380.0 - 2200.0),
    gainLossPercent: ((4380.0 - 2200.0) / 2200.0) * 100,
    dailyChangePercent: -2.14,
    targetWeight: 4,
    createdAt: '2023-02-10T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  // Cash
  {
    id: '10',
    symbol: 'USD-CASH',
    name: 'US Dollar Cash',
    assetType: 'cash',
    account: 'cash',
    quantity: 8500,
    costBasis: 1.0,
    currency: 'USD',
    exchange: '',
    currentPrice: 1.0,
    currentPriceCad: USD_CAD,
    marketValueCad: 8500 * USD_CAD,
    costValueCad: 8500 * USD_CAD,
    gainLoss: 0,
    gainLossPercent: 0,
    dailyChangePercent: 0,
    targetWeight: 6,
    createdAt: '2023-06-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  {
    id: '11',
    symbol: 'EUR-CASH',
    name: 'Euro Cash',
    assetType: 'cash',
    account: 'cash',
    quantity: 3000,
    costBasis: 1.0,
    currency: 'EUR',
    exchange: '',
    currentPrice: 1.0,
    currentPriceCad: EUR_CAD,
    marketValueCad: 3000 * EUR_CAD,
    costValueCad: 3000 * EUR_CAD,
    gainLoss: 0,
    gainLossPercent: 0,
    dailyChangePercent: 0,
    targetWeight: 2,
    createdAt: '2023-06-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
  {
    id: '12',
    symbol: 'CAD-CASH',
    name: 'Canadian Dollar Cash',
    assetType: 'cash',
    account: 'cash',
    quantity: 12500,
    costBasis: 1.0,
    currency: 'CAD',
    exchange: '',
    currentPrice: 1.0,
    currentPriceCad: 1.0,
    marketValueCad: 12500,
    costValueCad: 12500,
    gainLoss: 0,
    gainLossPercent: 0,
    dailyChangePercent: 0,
    targetWeight: 10,
    createdAt: '2023-06-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    indicatedAnnualDividend: null,
    indicatedAnnualDividendCurrency: null,
    dividendFrequency: null,
    maturityDate: null,
    fxStale: false,
    priceIsStale: false,
  },
];

function buildSnapshot(): PortfolioSnapshot {
  const totalValue = RAW_HOLDINGS.reduce((sum, h) => sum + h.marketValueCad, 0);
  const totalCost = RAW_HOLDINGS.reduce((sum, h) => sum + h.costValueCad, 0);

  const holdings: HoldingWithPrice[] = RAW_HOLDINGS.map((h) => ({
    ...h,
    weight: (h.marketValueCad / totalValue) * 100,
    targetValue: totalValue * (h.targetWeight / 100),
    targetDeltaValue: totalValue * (h.targetWeight / 100) - h.marketValueCad,
    targetDeltaPercent: h.targetWeight - (h.marketValueCad / totalValue) * 100,
  }));

  const totalGainLoss = totalValue - totalCost;
  const totalGainLossPercent = (totalGainLoss / totalCost) * 100;

  const dailyPnl = holdings.reduce(
    (sum, h) => sum + h.marketValueCad * (h.dailyChangePercent / 100),
    0
  );

  return {
    holdings,
    totalValue,
    totalCost,
    totalGainLoss,
    totalGainLossPercent,
    dailyPnl,
    lastUpdated: new Date().toISOString(),
    baseCurrency: 'CAD',
    totalTargetWeight: holdings.reduce((sum, h) => sum + h.targetWeight, 0),
    targetCashDelta: holdings
      .filter((holding) => holding.assetType === 'cash')
      .reduce((sum, holding) => sum + (holding.marketValueCad - holding.targetValue), 0),
    realizedGains: 0,
    annualDividendIncome: 0,
  };
}

export const MOCK_SNAPSHOT: PortfolioSnapshot = buildSnapshot();

/**
 * Build a minimal PortfolioSnapshot from a list of plain Holding objects.
 * Used in browser dev mode to keep the mock state consistent after mutations
 * (add/update/delete holding).
 */
export function buildMockSnapshot(holdingsList: Holding[]): PortfolioSnapshot {
  const totalValue = holdingsList.length * 1000;
  return {
    ...MOCK_SNAPSHOT,
    holdings: holdingsList.map((h) => ({
      ...h,
      currentPrice: h.costBasis,
      currentPriceCad: h.costBasis,
      marketValueCad: h.quantity * h.costBasis,
      costValueCad: h.quantity * h.costBasis,
      gainLoss: 0,
      gainLossPercent: 0,
      weight: totalValue > 0 ? (h.quantity * h.costBasis) / totalValue : 0,
      targetValue: 0,
      targetDeltaValue: 0,
      targetDeltaPercent: 0,
      dailyChangePercent: 0,
      fxStale: false,
      priceIsStale: false,
    })),
    totalValue,
    totalCost: totalValue,
    totalGainLoss: 0,
    totalGainLossPercent: 0,
    dailyPnl: 0,
    lastUpdated: new Date().toISOString(),
  };
}

export const MOCK_DIVIDENDS: Dividend[] = [
  {
    id: 1,
    holdingId: 'h1',
    symbol: 'VDY.TO',
    amountPerUnit: 0.118,
    currency: 'CAD',
    exDate: '2026-01-15',
    payDate: '2026-01-31',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 2,
    holdingId: 'h2',
    symbol: 'AAPL',
    amountPerUnit: 0.25,
    currency: 'USD',
    exDate: '2026-02-07',
    payDate: '2026-02-13',
    createdAt: '2026-01-20T00:00:00Z',
  },
];

export const MOCK_HOLDINGS: Holding[] = RAW_HOLDINGS.map(
  ({
    currentPrice: _1,
    currentPriceCad: _2,
    marketValueCad: _3,
    costValueCad: _4,
    gainLoss: _5,
    gainLossPercent: _6,
    dailyChangePercent: _7,
    ...h
  }) => h
);
