// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account = { id: string, name: string, accountType: string, institution: string | null, createdAt: string, };
