// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direction for a price alert threshold.
 */
export type AlertDirection = 'above' | 'below';
