// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes how a source column was mapped to a canonical holding field.
 */
export type ColumnMapping = { sourceHeader: string, canonicalField: string | null, 
/**
 * "exact" | "alias" | "profile" | "user" | "derived"
 */
confidence: string, reason: string, };
