// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { T5008Disposition } from "./T5008Disposition";
import type { T5IncomeRecord } from "./T5IncomeRecord";

/**
 * Discriminated result returned by `parse_cra_xml` — callers switch on
 * `kind` to decide which list to display.
 */
export type CraXmlResult = { "kind": "t5008", dispositions: Array<T5008Disposition>, } | { "kind": "t5", income: Array<T5IncomeRecord>, };
