// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingId } from "./HoldingId";

export type Dividend = { id: bigint, holdingId: HoldingId, symbol: string, amountPerUnit: number, currency: string, exDate: string, payDate: string, createdAt: string, };
