// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Dividend = { id: bigint, holdingId: string, symbol: string, amountPerUnit: number, currency: string, exDate: string, payDate: string, createdAt: string, };
