// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingId } from "./HoldingId";

export type DividendInput = { holdingId: HoldingId, amountPerUnit: number, currency: string, exDate: string, payDate: string, };
