// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dividend } from "./Dividend";
import type { Holding } from "./Holding";
import type { PriceAlert } from "./PriceAlert";
import type { Transaction } from "./Transaction";

/**
 * Full data export payload — includes all user data for backup/restore.
 */
export type ExportPayload = { holdings: Array<Holding>, alerts: Array<PriceAlert>, config: Array<[string, string]>, transactions: Array<Transaction>, dividends: Array<Dividend>, };
