// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountType } from "./AccountType";
import type { AssetType } from "./AssetType";

export type Holding = { id: string, symbol: string, name: string, assetType: AssetType, account: AccountType, accountId: string | null, accountName: string | null, quantity: number, costBasis: number, currency: string, exchange: string, targetWeight: number, createdAt: string, updatedAt: string, indicatedAnnualDividend: number | null, indicatedAnnualDividendCurrency: string | null, dividendFrequency: string | null, maturityDate: string | null, };
