// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountType } from './AccountType';
import type { AssetType } from './AssetType';

export type HoldingWithPrice = {
  id: string;
  symbol: string;
  name: string;
  assetType: AssetType;
  account: AccountType;
  accountId: string | null;
  accountName: string | null;
  quantity: number;
  costBasis: number;
  currency: string;
  exchange: string;
  targetWeight: number;
  createdAt: string;
  updatedAt: string;
  indicatedAnnualDividend: number | null;
  indicatedAnnualDividendCurrency: string | null;
  dividendFrequency: string | null;
  maturityDate: string | null;
  currentPrice: number;
  currentPriceCad: number;
  marketValueCad: number;
  costValueCad: number;
  gainLoss: number;
  gainLossPercent: number;
  weight: number;
  targetValue: number;
  targetDeltaValue: number;
  targetDeltaPercent: number;
  dailyChangePercent: number;
  /**
   * True when the FX rate for this holding's currency was not available;
   * values are shown in the source currency as a fallback.
   */
  fxStale: boolean;
};
