// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-supplied context applied to every row of an import unless the file
 * provides stronger per-row account information.
 */
export type ImportContext = { 
/**
 * TFSA, RRSP, FHSA, Taxable, Cash, Crypto, or Other.
 */
accountType: string, accountName: string | null, accountId: string | null, 
/**
 * Hint such as "CanadianBankMultiSection", "GenericCSV".
 */
sourceProfile: string | null, 
/**
 * User-selected column overrides: source column header -> canonical field name.
 */
columnOverrides: { [key in string]: string }, };
