// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NormalizedImportRow } from "./NormalizedImportRow";

/**
 * Selected rows to write to the DB, as chosen by the user in the review UI.
 */
export type ImportCommitRequest = { planRows: Array<NormalizedImportRow>, accountId: string, includeCash: boolean, };
