// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnMapping } from "./ColumnMapping";
import type { NormalizedImportRow } from "./NormalizedImportRow";

/**
 * Preview payload returned by `parse_import_file`. Never writes to the DB.
 */
export type ImportPlan = { profileDetected: string, columnMappings: Array<ColumnMapping>, rows: Array<NormalizedImportRow>, countCreate: number, countUpdate: number, countSkip: number, countNeedsFix: number, countWarning: number, suggestedAccountType: string | null, suggestedAccountNumber: string | null, cashRows: Array<NormalizedImportRow>, };
