// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Holding } from './Holding';
import type { ImportError } from './ImportError';

export type ImportResult = {
  imported: Array<Holding>;
  skipped: Array<ImportError>;
  totalRows: number;
};
