// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of committing an import plan, including insight deltas for the
 * post-import summary panel.
 */
export type ImportCommitResult = { created: number, updated: number, skipped: number, errors: Array<string>, newSymbols: Array<string>, changedSymbols: Array<string>, 
/**
 * Existing holdings in the target account not present in the imported file.
 * Surfaced as review candidates only — never auto-deleted.
 */
missingFromImport: Array<string>, staleSymbols: Array<string>, };
