// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RowAction } from "./RowAction";

/**
 * Canonical interpretation of one source row, produced by the row normalizer.
 */
export type NormalizedImportRow = { rowNumber: number, action: RowAction, symbol: string | null, resolvedSymbol: string | null, name: string | null, assetType: string | null, quantity: number | null, costBasis: number | null, 
/**
 * e.g. "average_cost", "derived:total_cost/qty"
 */
costBasisSource: string | null, currency: string | null, bookValue: number | null, marketValue: number | null, exchange: string | null, targetWeight: number | null, accountType: string, accountName: string | null, warnings: Array<string>, errors: Array<string>, 
/**
 * Original CSV values for this row, keyed by source header.
 */
raw: { [key in string]: string }, dividendYield: number | null, annualizedIncome: number | null, exDividendDate: string | null, };
