// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortfolioRiskMetrics = {
  weightedBeta: number | null;
  portfolioYield: number;
  largestPositionWeight: number;
  topSector: string | null;
  concentrationHhi: number;
};
