// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingWithPrice } from './HoldingWithPrice';

export type PortfolioSnapshot = {
  holdings: Array<HoldingWithPrice>;
  totalValue: number;
  totalCost: number;
  totalGainLoss: number;
  totalGainLossPercent: number;
  dailyPnl: number;
  lastUpdated: string;
  /**
   * The currency all values are expressed in (user-configurable, default "CAD").
   */
  baseCurrency: string;
  totalTargetWeight: number;
  targetCashDelta: number;
  /**
   * Sum of realized gains across all holdings (AVCO method, all-time).
   */
  realizedGains: number;
  /**
   * Sum of (amount_per_unit × quantity) for all dividends with a pay_date in the last 12 months.
   */
  annualDividendIncome: number;
};
