// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountryWeight } from "./CountryWeight";
import type { PortfolioRiskMetrics } from "./PortfolioRiskMetrics";
import type { SectorWeight } from "./SectorWeight";
import type { SymbolMetadata } from "./SymbolMetadata";

export type PortfolioAnalytics = { metadata: Array<SymbolMetadata>, riskMetrics: PortfolioRiskMetrics, sectorBreakdown: Array<SectorWeight>, countryBreakdown: Array<CountryWeight>, };
