// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewRow } from "./PreviewRow";

export type PreviewImportResult = { rows: Array<PreviewRow>, readyCount: number, skipCount: number, };
