// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewRow = { row: number, 
/**
 * Symbol as written in the CSV (e.g. "BMO:CA")
 */
originalSymbol: string, 
/**
 * Resolved Yahoo Finance symbol (e.g. "BMO.TO"), empty when unresolvable
 */
resolvedSymbol: string, name: string, assetType: string, currency: string, exchange: string, quantity: number, costBasis: number, targetWeight: number, 
/**
 * "ready" | "cash" | "duplicate" | "invalid_symbol" | "validation_failed"
 */
status: string, };
