// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertDirection } from "./AlertDirection";

export type PriceAlertInput = { symbol: string, direction: AlertDirection, threshold: number, currency: string, note: string, };
