// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertDirection } from "./AlertDirection";
import type { AlertId } from "./AlertId";

export type PriceAlert = { id: AlertId, symbol: string, direction: AlertDirection, threshold: number, currency: string, note: string, triggered: boolean, createdAt: string, };
