// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PriceData = { symbol: string, price: number, currency: string, change: number, changePercent: number, updatedAt: string, open: number | null, previousClose: number | null, volume: bigint | null, };
