// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One matched lot that was sold.
 */
export type RealizedLot = { 
/**
 * ISO date of the sell transaction (YYYY-MM-DD).
 */
soldAt: string, quantity: number, 
/**
 * quantity × sell_price
 */
proceeds: number, 
/**
 * quantity × cost_per_unit (method-dependent)
 */
costBasis: number, 
/**
 * proceeds − cost_basis
 */
gainLoss: number, };
