// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealizedLot } from './RealizedLot';

export type RealizedGainsSummary = {
  totalRealizedGain: number;
  totalProceeds: number;
  totalCostBasis: number;
  lots: Array<RealizedLot>;
};
