// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RebalanceSuggestion = {
  holdingId: string;
  symbol: string;
  name: string;
  currentValueCad: number;
  targetValueCad: number;
  currentWeight: number;
  targetWeight: number;
  drift: number;
  suggestedTradeCad: number;
  suggestedUnits: number;
  currentPriceCad: number;
};
