// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceData } from "./PriceData";

/**
 * Returned by the `refresh_prices` command.
 * Separates successfully refreshed prices from symbols that failed.
 */
export type RefreshResult = { prices: Array<PriceData>, 
/**
 * Symbols for which the price fetch failed (network error, HTTP error, parse failure).
 */
failedSymbols: Array<string>, 
/**
 * IDs of price alerts that were triggered during this refresh.
 */
triggeredAlerts: Array<string>, 
/**
 * Human-readable errors that occurred while evaluating price alerts.
 * Non-empty when one or more alert checks failed so the frontend can surface them.
 */
alertErrors: Array<string>, };
