// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The action the import plan proposes for a given row.
 */
export type RowAction = "create" | "update" | "skip" | "needs_fix" | "warning";
