// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingId } from "./HoldingId";

export type StressHoldingResult = { holdingId: HoldingId, symbol: string, name: string, currentValue: number, stressedValue: number, impact: number, shockApplied: number, };
