// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StressHoldingResult } from "./StressHoldingResult";

export type StressResult = { scenario: string, currentValue: number, stressedValue: number, totalImpact: number, totalImpactPercent: number, holdingBreakdown: Array<StressHoldingResult>, };
