// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SymbolMetadata = {
  symbol: string;
  sector: string | null;
  industry: string | null;
  country: string | null;
  marketCap: number | null;
  peRatio: number | null;
  dividendYield: number | null;
  beta: number | null;
  eps: number | null;
};
