// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetType } from "./AssetType";

export type SymbolResult = { symbol: string, name: string, assetType: AssetType, exchange: string, currency: string, };
