// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single securities-disposition record parsed from a CRA T5008 XML file.
 * Maps to Statement of Securities Transactions (Box 15–21).
 */
export type T5008Disposition = { 
/**
 * Security description (Box 17: id_scty_dsps_txt).
 */
name: string, 
/**
 * Mapped asset type string derived from T5008 security type code (Box 15).
 * One of "stock", "etf", "other".
 */
assetType: string, 
/**
 * Units disposed (Box 16: dsps_scty_cnt).
 */
quantity: number | null, 
/**
 * CUSIP or ISIN identifier (Box 18: dsps_cusip_nbr).
 */
cusipIsin: string | null, 
/**
 * ISO 4217 currency (Box 13: fgn_crcy_cd); defaults to "CAD".
 */
currency: string, 
/**
 * Total cost or book value (Box 20: cost_bok_val_amt).
 */
bookValue: number | null, 
/**
 * Proceeds of disposition (Box 21: dispn_amt).
 */
proceeds: number | null, 
/**
 * Taxation year from T5008Summary.
 */
taxYear: number, 
/**
 * Broker-assigned account number (ident_record: rcpnt_acct_nbr).
 */
accountNumber: string | null, };
