// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single income record parsed from a CRA T5 XML file.
 * Maps to Statement of Investment Income fields.
 */
export type T5IncomeRecord = { 
/**
 * Income type: one of "dividend_eligible", "dividend_non_eligible",
 * "interest", "foreign_income", "other_canadian", "royalty",
 * "capital_gains_dividend".
 */
incomeType: string, 
/**
 * Dollar amount of the income.
 */
amount: number, 
/**
 * ISO 4217 currency (Box 27: fgn_crcy_ind); defaults to "CAD".
 */
currency: string, 
/**
 * Foreign tax paid (Box 16: fgn_tx_pay_amt), if any.
 */
withholdingTax: number | null, 
/**
 * Taxation year from T5Summary.
 */
taxYear: number, 
/**
 * Broker-assigned account number (Box 29: rcpnt_fi_acct_nbr).
 */
accountNumber: string | null, };
