// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionType } from './TransactionType';

export type TransactionInput = {
  holdingId: string;
  transactionType: TransactionType;
  quantity: number;
  price: number;
  transactedAt: string;
};
