// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingId } from "./HoldingId";
import type { TransactionId } from "./TransactionId";
import type { TransactionType } from "./TransactionType";

/**
 * A single buy or sell transaction for a holding.
 */
export type Transaction = { id: TransactionId, holdingId: HoldingId, 
/**
 * "buy" | "sell"
 */
transactionType: TransactionType, quantity: number, 
/**
 * Price per unit in the holding's original currency.
 */
price: number, 
/**
 * ISO 8601 timestamp of when the transaction occurred.
 */
transactedAt: string, createdAt: string, };
