// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchlistId } from "./WatchlistId";
import type { WatchlistItemId } from "./WatchlistItemId";

/**
 * A watchlist item joined with its most recently fetched market-data
 * snapshot (if any). `retrieved_at` is `None` when the item has never been
 * refreshed; `is_stale` is `true` when the snapshot is older than 15
 * minutes. `snapshot_error` carries the last fetch failure, if any, so the
 * UI can show a per-row error state without hiding the rest of the item's
 * research fields.
 */
export type WatchlistItemWithSnapshot = { id: WatchlistItemId, watchlistId: WatchlistId, symbol: string, name: string | null, currency: string, thesis: string | null, catalysts: string | null, risks: string | null, entryPriceLow: number | null, entryPriceHigh: number | null, createdAt: string, updatedAt: string, price: number | null, marketCap: number | null, fiftyTwoWeekLow: number | null, fiftyTwoWeekHigh: number | null, ytdReturn: number | null, oneYearReturn: number | null, dividendYield: number | null, peRatio: number | null, retrievedAt: string | null, isStale: boolean, snapshotError: string | null, };
