// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchlistId } from "./WatchlistId";

/**
 * A named research watchlist.
 */
export type Watchlist = { id: WatchlistId, name: string, createdAt: string, updatedAt: string, };
